# Generated by Django 4.0.4 on 2022-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='available',
            field=models.IntegerField(),
        ),
    ]
