# Generated by Django 4.0.4 on 2022-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpostapp', '0003_remove_appointment_img_remove_appointment_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
