# Generated by Django 4.0.4 on 2022-07-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpostapp', '0004_medicine_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
