# Generated by Django 4.0.4 on 2022-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpostapp', '0006_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
